# Generated by Django 2.2.10 on 2020-02-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='D:\\python\\jsclub-project\\static\\avatar.png', upload_to='images/'),
        ),
    ]
