# Generated by Django 2.2.10 on 2020-03-02 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200221_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 22, 29, 35, 465457)),
        ),
    ]
