# Generated by Django 2.2.10 on 2020-03-04 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200302_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='/Users/macbook/Desktop/mygit/jsclub-django-2/static/avatar.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 4, 49, 6, 51320)),
        ),
    ]
