# Generated by Django 2.2.10 on 2020-03-04 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200304_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 4, 53, 56, 465314)),
        ),
    ]
