# Generated by Django 2.2.10 on 2020-03-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200303_1858'),
        ('account', '0009_auto_20200304_1609'),
    ]

    operations = [
    ]
