# Generated by Django 2.2.10 on 2020-03-05 12:34

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_merge_20200305_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='firstname',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='account',
            name='lastname',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='c:\\JS\\Git\\safe\\static\\avatar.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 3, 5, 19, 34, 45, 514726)),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
