# Generated by Django 2.2.10 on 2020-03-05 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200305_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 3, 5, 19, 43, 41, 209355)),
        ),
    ]
