# Generated by Django 2.2.10 on 2020-03-05 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20200305_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 3, 5, 19, 48, 34, 929817)),
        ),
        migrations.AlterField(
            model_name='account',
            name='firstname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='account',
            name='lastname',
            field=models.CharField(max_length=60),
        ),
    ]
