# Generated by Django 2.2.10 on 2020-02-21 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200215_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='C:\\Users\\VanNam\\Desktop\\jsclub-django\\static\\avatar.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 10, 40, 24, 46688)),
        ),
    ]
